package sk.t_systems.rmc.ds.bwl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-03T22:50:36.821+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "score", 
                  wsdlLocation = "file:/home/adam/projects/temp/gs-consuming-web-service/wsdlCreatorGradle/src/main/resources/wsdl/bwl_1_1.wsdl",
                  targetNamespace = "t-systems.sk/rmc/ds/bwl") 
public class Score_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("t-systems.sk/rmc/ds/bwl", "score");
    public final static QName BWLendpoint = new QName("t-systems.sk/rmc/ds/bwl", "BWLendpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/adam/projects/temp/gs-consuming-web-service/wsdlCreatorGradle/src/main/resources/wsdl/bwl_1_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Score_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/adam/projects/temp/gs-consuming-web-service/wsdlCreatorGradle/src/main/resources/wsdl/bwl_1_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Score_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Score_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Score_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Score_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Score_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Score_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ScorePortType
     */
    @WebEndpoint(name = "BWLendpoint")
    public ScorePortType getBWLendpoint() {
        return super.getPort(BWLendpoint, ScorePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ScorePortType
     */
    @WebEndpoint(name = "BWLendpoint")
    public ScorePortType getBWLendpoint(WebServiceFeature... features) {
        return super.getPort(BWLendpoint, ScorePortType.class, features);
    }

}
