
package sk.t_systems.rmc.ds.score;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-03T22:50:37.028+02:00
 * Generated source version: 3.1.6
 */

@WebFault(name = "DataServiceFault", targetNamespace = "http://ws.wso2.org/dataservice")
public class DataServiceFault extends Exception {
    
    private org.wso2.ws.dataservice.DataServiceFault dataServiceFault;

    public DataServiceFault() {
        super();
    }
    
    public DataServiceFault(String message) {
        super(message);
    }
    
    public DataServiceFault(String message, Throwable cause) {
        super(message, cause);
    }

    public DataServiceFault(String message, org.wso2.ws.dataservice.DataServiceFault dataServiceFault) {
        super(message);
        this.dataServiceFault = dataServiceFault;
    }

    public DataServiceFault(String message, org.wso2.ws.dataservice.DataServiceFault dataServiceFault, Throwable cause) {
        super(message, cause);
        this.dataServiceFault = dataServiceFault;
    }

    public org.wso2.ws.dataservice.DataServiceFault getFaultInfo() {
        return this.dataServiceFault;
    }
}
